[WIP] Feature/vizbox
tue-robotics/robot_launch_files pull request #26
Opened 2018-02-20 21:06 UTC by LoyVanBeek

2018-05-03 20:08 UTC, MatthijsBurgh commented on launch/interaction/vizbox.launch
> +        args="/$(arg robot_name)/hmi/result hmi/result/sentence std_msgs/String 'm.result.sentence'"/>
Or include this launch file in the robot ns?

2018-05-03 21:00 UTC, LoyVanBeek commented on launch/interaction/vizbox.launch
> +        args="/$(arg robot_name)/hmi/result hmi/result/sentence std_msgs/String 'm.result.sentence'"/>
It is, but topic_tools doesn't handle namespaces AFAICT. 
hmi/result is in the same namepace and the ROS namespacing works for that.

2018-05-03 21:05 UTC, LoyVanBeek commented on launch/interaction/vizbox.launch
> +        args="/$(arg robot_name)/hmi/result hmi/result/sentence std_msgs/String 'm.result.sentence'"/>
Of course I tried without ```/$(arg robot_name)/```, but that results in an error:

```
ERROR: Wrong input topic (or topic field): hmi/result
[amigo/extract_hmi_result_sentence-18] process has died [pid 12326, exit code 1, cmd /opt/ros/kinetic/lib/topic_tools/transform hmi/result hmi/result/sentence std_msgs/String m.result.sentence __name:=extract_hmi_result_sentence __log:=/home/loy/.ros/log/7310f27a-4d6e-11e8-bcb2-d07e35c47b06/amigo-extract_hmi_result_sentence-18.log].
log file: /home/loy/.ros/log/7310f27a-4d6e-11e8-bcb2-d07e35c47b06/amigo-extract_hmi_result_sentence-18*.log
```

2018-05-03 21:05 UTC, MatthijsBurgh commented on launch/interaction/vizbox.launch
> +        args="/$(arg robot_name)/hmi/result hmi/result/sentence std_msgs/String 'm.result.sentence'"/>
👍

2018-05-12 14:32 UTC, jlunenburg requested changes
Have a look at the comments. If you don't use a machine files, don't include them? Furthermore, did you test this on the robot?

2018-05-12 14:32 UTC, jlunenburg commented on launch/interaction/vizbox.launch
> +    <arg name="machine" default="localhost"/>
I guess machine files aren't used anymore?!

2018-05-12 14:32 UTC, jlunenburg commented on launch/interaction/vizbox.launch
> +        <remap to="text_to_speech/output" from="robot_text"/>
Being picky, isn't it easier to read from .. to?

2018-05-12 14:32 UTC, jlunenburg commented on launch/interaction/vizbox.launch
> +    <node pkg="vizbox" type="server.py" name="vizbox" cwd="node" output="log">
Is vizbox installed by default?

2018-05-12 15:21 UTC, LoyVanBeek commented on launch/interaction/vizbox.launch
> +    <node pkg="vizbox" type="server.py" name="vizbox" cwd="node" output="log">
https://github.com/tue-robotics/tue-env/pull/261

2018-05-12 15:22 UTC, LoyVanBeek commented on launch/interaction/vizbox.launch
> +    <arg name="machine" default="localhost"/>
Yes they are, all the state machine launches declare which machine to run each node in. I just forgot to pass that on to the actual node

2018-09-23 15:27 UTC, MatthijsBurgh commented
@LoyVanBeek please decide what to with the vizbox.

2018-09-25 15:09 UTC, LoyVanBeek commented
I think it's handy for us to have regards of RoboCup, so I'd say merge it ASAP

2019-02-05 18:37 UTC, LoyVanBeek commented
Nobody cares

2019-04-28 06:42 UTC, MatthijsBurgh requested changes

2019-04-28 06:42 UTC, MatthijsBurgh commented on launch/interaction/vizbox.launch
> +    <include file="$(env ROBOT_BRINGUP_PATH)/machines/$(arg machine).machine" />
better to put this `include` directly after the machine argument.

2019-04-28 06:42 UTC, MatthijsBurgh commented on launch/interaction/vizbox.launch
> +        args="/$(arg robot_name)/hmi/result hmi/result/sentence std_msgs/String 'm.result.sentence'"/>
But does it output to `/robot_name/hmi/result/sentence`? Or to `hmi/result/sentence`? What is the desired behaviour? It is without the robot name. Please make it absolute.

2019-05-23 08:52 UTC, merged