Add topic mode arg to people recognition
tue-robotics/robot_launch_files pull request #48
Opened 2019-06-05 07:27 UTC by ar13pit

2019-06-08 15:05 UTC, MatthijsBurgh requested changes

2019-06-08 15:05 UTC, MatthijsBurgh commented on launch/world_modeling/people_recognition.launch
> +    <arg name="probability_threshold" default="0.2" />
This is too much, it should be in a config file.

2020-03-04 14:08 UTC, ar13pit commented
@PetervDooren can this PR be closed?

2020-03-04 14:13 UTC, PetervDooren commented
I think it can as it solves the same problem as PR #55

2020-03-04 14:22 UTC, closed without merging