use config
tue-robotics/robot_launch_files pull request #67
Opened 2021-06-15 19:36 UTC by PetervDooren

2021-06-15 20:13 UTC, MatthijsBurgh commented
The config should be an argument. With the current value as default.

2021-06-15 21:23 UTC, ar13pit requested changes, later dismissed

2021-06-15 21:23 UTC, ar13pit commented on launch/world_modeling/people_recognition.launch
> +                <rosparam command="load" file="$(find people_recognition_3d)/config/config.yaml" />
I agree with Matthijs

2021-06-21 18:15 UTC, MatthijsBurgh requested changes

2021-06-21 18:15 UTC, MatthijsBurgh commented on launch/world_modeling/people_recognition.launch
> +    <arg name="config_file" default="$(find people_recognition_3d)/config/config.yaml" />
The config is for `people_recognition_3d`. As multiple nodes are launched in this file, I think this should be represented in the name.

2021-06-22 16:28 UTC, MatthijsBurgh approved these changes

2021-06-22 16:54 UTC, merged